#ifndef SERVER_DEFINITIONS_H
#define SERVER_DEFINITIONS_H

#define QUEUE_MAX_MESSAGES 10
#define QUEUE_PAYLOAD_SIZE 256

#define MESSAGE_BUFFER_SIZE QUEUE_PAYLOAD_SIZE
#define MESSAGE_FORMATTING_SIZE 16
#define MESSAGE_SIZE (MESSAGE_BUFFER_SIZE + MESSAGE_FORMATTING_SIZE)

#define SOCKET_MAX_CONNECTIONS 256
#define QUEUE_NAME "/s2_server"

#define RECENT_MESSAGE_SIZE 100

#endif //SERVER_DEFINITIONS_H
