#ifndef SERVER_DEFINITIONS_H
#define SERVER_DEFINITIONS_H


#define QUEUE_NAME "/c_server"
#define QUEUE_MAX_MESSAGES 16
#define QUEUE_PAYLOAD_SIZE 256
#define QUEUE_PERMISSIONS 0660

#define MESSAGE_BUFFER_SIZE QUEUE_PAYLOAD_SIZE
#define MESSAGE_SIZE (MESSAGE_BUFFER_SIZE + MESSAGE_FORMATTING_SIZE)
#define MESSAGE_FORMATTING_SIZE 16
#define MESSAGE_ALLOWED_SYMBOLS "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789()?!,;:&*+@$%^/><'.-_\r\n "
#define RECENT_MESSAGES_SIZE 100

#define SOCKET_MAX_CONNECTIONS 256
#define PORT 6969


#endif //SERVER_DEFINITIONS_H
